apiVersion: v1
kind: Namespace
metadata:
  name: workspaceservice
  labels:
    name: workspaceservice
    app: workspaceservice
---
apiVersion: v1
kind: LimitRange
metadata:
  name: workspaceservice-limit-range
  namespace: workspaceservice
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container